// כל טקסטי הממשק בעברית — אין hardcode בקומפוננטות

export const STRINGS = {
  app: {
    name: 'SmartHome',
    tagline: 'בית חכם — ניהול משפחתי',
  },
  auth: {
    signIn: 'כניסה עם Google',
    welcome: 'ברוכים הבאים',
    subtitle: 'ניהול חכם של הבית שלך',
    waitingApproval: 'ממתין לאישור מנהל',
    notApproved: 'החשבון שלך ממתין לאישור',
  },
  nav: {
    dashboard: 'דשבורד',
    tasks: 'משימות',
    shopping: 'קניות',
    budget: 'תקציב',
    calendar: 'לוח שנה',
    events: 'אירועים',
    gifts: 'מתנות',
    inventory: 'מלאי',
    medical: 'רפואה',
    vehicle: 'רכב',
    gamification: 'לוח מובילים',
    settings: 'הגדרות',
  },
  tasks: {
    title: 'משימות בית',
    add: 'הוסף משימה',
    done: 'בוצע',
    doneBy: 'בוצע על ידי',
    assignTo: 'שייך אל',
    priority: { high: 'דחוף', medium: 'רגיל', low: 'יכול לחכות' },
    points: { high: 30, medium: 20, low: 10 },
    categories: ['ניקיון', 'בישול', 'קניות', 'ילדים', 'כללי'],
  },
  shopping: {
    title: 'רשימת קניות',
    add: 'הוסף מוצר',
    done: 'נרכש',
    clear: 'נקה שנרכשו',
  },
  budget: {
    title: 'ניהול תקציב',
    income: 'הכנסות',
    expense: 'הוצאות',
    balance: 'יתרה',
    warning: 'הגעת ל־80% מהתקציב החודשי',
    categories: ['מזון', 'תחבורה', 'חינוך', 'בריאות', 'בידור', 'כללי'],
  },
  calendar: {
    title: 'לוח שנה',
    addEvent: 'הוסף אירוע',
    upcoming: 'אירועים קרובים',
  },
  events: {
    title: 'אירועים',
    types: {
      birthday: 'יום הולדת',
      wedding: 'חתונה',
      barmitzvah: 'בר/בת מצווה',
      medical: 'תור רפואי',
      other: 'אחר',
    },
  },
  gifts: {
    title: 'מעקב מתנות',
    gave: 'נתתי',
    received: 'קיבלתי',
    lastEvent: 'אירוע אחרון',
    addGift: 'הוסף רשומה',
    noAmountRecommendation: 'אין המלצות סכום',
  },
  inventory: {
    title: 'מלאי הבית',
    add: 'הוסף פריט',
    lowStock: 'מלאי נמוך',
    categories: ['מזון', 'ניקיון', 'אישי', 'כללי'],
  },
  medical: {
    title: 'תיק רפואי',
    addRecord: 'הוסף רשומה',
    medications: 'תרופות',
    allergies: 'אלרגיות',
    appointments: 'תורים',
  },
  vehicle: {
    title: 'ניהול רכב',
    test: 'טסט',
    insurance: 'ביטוח',
    fuel: 'יומן דלק',
    addFuel: 'הוסף תדלוק',
    expiringSoon: 'פג תוקף בקרוב',
  },
  gamification: {
    title: 'לוח מובילים',
    weeklyPoints: 'נקודות השבוע',
    totalPoints: 'סה״כ נקודות',
    resetWeekly: 'איפוס שבועי אוטומטי',
    badges: {
      topCleaner: 'מנקה השבוע',
      shoppingChamp: 'אלוף הקניות',
      taskMaster: 'מלך המשימות',
    },
  },
  errors: {
    general: 'אירעה שגיאה, נסה שוב',
    noPermission: 'אין לך הרשאה לפעולה זו',
    networkError: 'בעיית תקשורת, בדוק חיבור לאינטרנט',
    notFound: 'הרשומה לא נמצאה',
  },
  success: {
    saved: 'נשמר בהצלחה',
    deleted: 'נמחק בהצלחה',
    updated: 'עודכן בהצלחה',
  },
  confirm: {
    delete: 'האם אתה בטוח שברצונך למחוק?',
    yes: 'כן',
    no: 'לא',
  },
};
